services:
  inbox-creeper:
    build:
      context: https://github.com/dankreek/inbox-creeper.git
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
